import AppKit
import ImageIO
import UniformTypeIdentifiers

/// 剪贴板监控 — 每 `pollingInterval` 秒检查 NSPasteboard.changeCount
@MainActor
final class ClipboardMonitor: ObservableObject {
    /// 轮询间隔（秒）。500ms 是 Raycast / Paste / Maccy 等同类工具的常见取舍：
    /// 更短会增加唤醒频率和电量消耗，更长会让"刚复制立即唤起"产生肉眼可感的延迟。
    private static let pollingInterval: TimeInterval = 0.5

    /// 单条文本最大字节数（10MB）。超过时跳过持久化：
    /// 大文本通常是终端 dump、整本 PDF 文本提取等极端场景；10MB 能覆盖绝大多数"我真想保存"的长文本，
    /// 同时防止个别极端条目把 DB 撑大、拖慢 FTS 重建。
    private static let maxTextBytes = 10 * 1024 * 1024

    private enum PasteboardMetadata {
        static let sourceBundleID = NSPasteboard.PasteboardType("org.nspasteboard.source")
        static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
        static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
        static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

        static let sensitiveTypes: Set<NSPasteboard.PasteboardType> = [
            concealed,
            transient,
            autoGenerated
        ]
    }

    private enum ClipboardPayload: Sendable {
        case text(String, String?, String?, [ClipboardRepresentation])
        case url(String, String?, String?, [ClipboardRepresentation])
        case file(String, String?, String?)
        case image(Data, String?, String?)
    }

    private let core: ClipinCore
    private let settings: SettingsStore
    private var timer: Timer?
    private var lastChangeCount: Int
    private var isPaused = false
    /// 持有所有正在跑的 persist task，stop() 时统一取消。
    /// 旧实现 Task.detached 启动后没有持有引用，监控停止/进程退出时正在跑的图片 OCR
    /// 仍会继续 Vision 调用并发通知，破坏 launcher 关闭后"什么都不再变"的语义。
    /// 取消不会 abort 已经开始的 SQLite write，但 OCR 段（recognizeText）会响应。
    private var inflightPersists: Set<Task<Void, Never>> = []

    init(core: ClipinCore, settings: SettingsStore) {
        self.core = core
        self.settings = settings
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        guard timer == nil else { return }
        timer = Timer.scheduledTimer(withTimeInterval: Self.pollingInterval, repeats: true) { [weak self] _ in
            Task { @MainActor in
                self?.checkClipboard()
            }
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        let pending = inflightPersists
        inflightPersists.removeAll()
        pending.forEach { $0.cancel() }
    }

    /// 暂停监控（粘贴时用，避免把自己写入的内容又存一遍）
    func pause() {
        isPaused = true
    }

    /// 恢复监控，跳过暂停期间的变化
    func resume() {
        lastChangeCount = NSPasteboard.general.changeCount
        isPaused = false
    }

    var onNewItem: (() -> Void)?

    private func checkClipboard() {
        guard !isPaused else { return }

        let pasteboard = NSPasteboard.general
        let currentCount = pasteboard.changeCount
        guard currentCount != lastChangeCount else { return }
        lastChangeCount = currentCount

        guard shouldPersistContents(of: pasteboard) else { return }

        let source = resolveSourceApp(from: pasteboard)
        let sourceApp = source.bundleIdentifier
        let sourceName = source.appName

        // 高层语义优先，低层二进制兜底
        // file → url → image → text
        if let fileURLs = pasteboard.readObjects(forClasses: [NSURL.self], options: [
            .urlReadingFileURLsOnly: true
        ]) as? [URL], !fileURLs.isEmpty {
            let paths = fileURLs.map(\.path)
            persist(.file(FileClipboardContent.encodedContent(from: paths), sourceApp, sourceName))
        } else if let urlString = pasteboard.string(forType: .URL) ?? extractURL(from: pasteboard) {
            let reps = ClipboardRepresentationExtractor.extract(from: pasteboard, primaryContent: urlString)
            persist(.url(urlString, sourceApp, sourceName, reps))
        } else if let imageData = pasteboard.data(forType: .tiff) ?? pasteboard.data(forType: .png) {
            persist(.image(imageData, sourceApp, sourceName))
        } else if let text = pasteboard.string(forType: .string), !text.isEmpty {
            // 超大文本（终端 dump、整本电子书等）跳过：FTS 重建会卡，磁盘也会被吃光
            if text.utf8.count > Self.maxTextBytes {
                print("ℹ️ Skipped clipboard text larger than \(Self.maxTextBytes) bytes")
                return
            }
            let reps = ClipboardRepresentationExtractor.extract(from: pasteboard, primaryContent: text)
            persist(.text(text, sourceApp, sourceName, reps))
        }
    }

    private func persist(_ payload: ClipboardPayload) {
        let core = self.core

        // 自引用 box：task body 完成时回主线程从 inflightPersists 移除自己，避免集合无限增长。
        // 用 Box<Task?> 是因为 Task 创建时还没拿到自身引用——先建 box、Task 内闭包持有 box、
        // Task 创建后写入 box，闭包 defer 时通过 box 拿到 task 引用。
        let box = TaskBox()
        let task = Task.detached(priority: .utility) { [weak self] in
            defer {
                // 显式把 weak self 重新 capture 进 inner Task：Swift 6 严格 isolation 下
                // 直接在 detached body 的 defer 里捕获外层 weak self 会被判为跨 actor
                // 边界 send 引用（即使 Monitor 是 @MainActor 也不行）。重 capture 后就是
                // 一次普通的 MainActor 任务调度。
                let monitor = self
                Task { @MainActor in
                    guard let task = box.task else { return }
                    monitor?.inflightPersists.remove(task)
                }
            }
            do {
                switch payload {
                case let .text(content, sourceApp, sourceName, reps):
                    let coreReps = reps.map { ClipRepresentation(uti: $0.uti, data: $0.data) }
                    _ = try core.saveItemWithRepresentations(
                        content: content,
                        clipType: .text,
                        sourceApp: sourceApp,
                        sourceName: sourceName,
                        imagePath: nil,
                        representations: coreReps
                    )

                case let .url(content, sourceApp, sourceName, reps):
                    let coreReps = reps.map { ClipRepresentation(uti: $0.uti, data: $0.data) }
                    _ = try core.saveItemWithRepresentations(
                        content: content,
                        clipType: .url,
                        sourceApp: sourceApp,
                        sourceName: sourceName,
                        imagePath: nil,
                        representations: coreReps
                    )

                case let .file(path, sourceApp, sourceName):
                    _ = try core.saveItem(
                        content: path,
                        clipType: .file,
                        sourceApp: sourceApp,
                        sourceName: sourceName,
                        imagePath: nil
                    )

                case let .image(data, sourceApp, sourceName):
                    let imageDir = core.imageDir()
                    let filename = UUID().uuidString + ".png"
                    let path = (imageDir as NSString).appendingPathComponent(filename)
                    let pngData = try Self.makePNGData(from: data)
                    try pngData.write(to: URL(fileURLWithPath: path), options: .atomic)
                    let saved = try core.saveItem(
                        content: "image",
                        clipType: .image,
                        sourceApp: sourceApp,
                        sourceName: sourceName,
                        imagePath: path
                    )
                    // 图片入库后立即刷新列表，让条目即时出现，不等 OCR
                    guard let self else { return }
                    await self.notifyNewItem()

                    // stop() 取消后，DB 已经写完不能撤销，但 OCR/通知都跳过，
                    // 避免 launcher 关闭后还冒出"OCR 完成"广播。
                    if Task.isCancelled { return }

                    // OCR 在同一后台 Task 内串行执行，完成后二次刷新显示文字
                    // 无论是否识别到文字都写回（NULL=未处理，""=处理过但无文字，避免重复 backfill）
                    let itemId = saved.id
                    let ocrText = await OcrService.recognizeText(at: path)
                    if Task.isCancelled { return }
                    do {
                        try core.updateOcrText(id: itemId, ocrText: ocrText)
                        if !ocrText.isEmpty {
                            NotificationCenter.default.post(name: .clipboardItemOcrUpdated, object: nil)
                        }
                    } catch {
                        if case ClipinError.NotFound = error {
                            // 图片在 OCR 期间被去重替换（连续复制同一图片），OCR 结果丢弃是预期行为
                            print("ℹ️ OCR result discarded: item \(itemId) was replaced by dedup")
                        } else {
                            print("⚠️ Failed to write OCR result: \(error)")
                        }
                    }
                    return  // image case 已自行通知，跳过下方公共 notifyNewItem
                }

                guard let self else { return }
                await self.notifyNewItem()
            } catch {
                print("⚠️ Failed to persist clipboard item: \(error)")
            }
        }
        box.task = task
        inflightPersists.insert(task)
    }

    private func shouldPersistContents(of pasteboard: NSPasteboard) -> Bool {
        let types = Set(pasteboard.types ?? [])

        // ConcealedType：密码管理器等明确标记的敏感内容，始终跳过
        if types.contains(PasteboardMetadata.concealed) {
            return false
        }

        // TransientType / AutoGeneratedType：临时或自动生成内容，由用户设置决定
        if settings.skipTransientContent {
            let transientTypes: Set<NSPasteboard.PasteboardType> = [
                PasteboardMetadata.transient,
                PasteboardMetadata.autoGenerated,
            ]
            if !types.isDisjoint(with: transientTypes) {
                return false
            }
        }

        if let sourceBundleID = pasteboard.string(forType: PasteboardMetadata.sourceBundleID),
           sourceBundleID == Bundle.main.bundleIdentifier {
            return false
        }

        return true
    }

    private func resolveSourceApp(from pasteboard: NSPasteboard) -> (bundleIdentifier: String?, appName: String?) {
        if let bundleIdentifier = pasteboard.string(forType: PasteboardMetadata.sourceBundleID),
           !bundleIdentifier.isEmpty {
            let appName = NSRunningApplication
                .runningApplications(withBundleIdentifier: bundleIdentifier)
                .first?
                .localizedName
            return (bundleIdentifier, appName)
        }

        let tracker = SourceAppTracker.shared
        return (tracker.bundleIdentifier, tracker.appName)
    }

    private func extractURL(from pasteboard: NSPasteboard) -> String? {
        guard let text = pasteboard.string(forType: .string),
              let url = URL(string: text),
              let scheme = url.scheme,
              ["http", "https"].contains(scheme) else { return nil }
        return text
    }

    nonisolated private static func makePNGData(from data: Data) throws -> Data {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil),
              let image = CGImageSourceCreateImageAtIndex(source, 0, nil) else {
            throw ClipboardMonitorError.invalidImageData
        }

        let output = NSMutableData()
        guard let destination = CGImageDestinationCreateWithData(
            output,
            UTType.png.identifier as CFString,
            1,
            nil
        ) else {
            throw ClipboardMonitorError.failedToEncodePNG
        }

        CGImageDestinationAddImage(destination, image, nil)
        guard CGImageDestinationFinalize(destination) else {
            throw ClipboardMonitorError.failedToEncodePNG
        }

        return output as Data
    }

    @MainActor
    private func notifyNewItem() {
        NotificationCenter.default.post(name: .clipHistoryItemSaved, object: nil)
        onNewItem?()
    }
}

private enum ClipboardMonitorError: Error {
    case invalidImageData
    case failedToEncodePNG
}

/// 给 Task body 一个延迟回填 task 引用的容器：Task 创建时拿不到自己的 handle，
/// 但 body defer 时需要它来从 inflightPersists 移除——typed box 避开循环引用陷阱。
@MainActor
private final class TaskBox {
    var task: Task<Void, Never>?
}
