import AppKit
import ImageIO
import UniformTypeIdentifiers

/// 剪贴板监控 — 每 `pollingInterval` 秒检查 NSPasteboard.changeCount
@MainActor
final class ClipboardMonitor: ObservableObject {
    /// 轮询间隔（秒）。500ms 是 Raycast / Paste / Maccy 等同类工具的常见取舍：
    /// 更短会增加唤醒频率和电量消耗，更长会让"刚复制立即唤起"产生肉眼可感的延迟。
    private static let pollingInterval: TimeInterval = 0.5

    /// 单条文本最大字节数（10MB）。超过时跳过持久化：
    /// 大文本通常是终端 dump、整本 PDF 文本提取等极端场景；10MB 能覆盖绝大多数"我真想保存"的长文本，
    /// 同时防止个别极端条目把 DB 撑大、拖慢 FTS 重建。
    private static let maxTextBytes = 10 * 1024 * 1024

    private enum PasteboardMetadata {
        static let sourceBundleID = NSPasteboard.PasteboardType("org.nspasteboard.source")
        static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
        static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
        static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

        static let sensitiveTypes: Set<NSPasteboard.PasteboardType> = [
            concealed,
            transient,
            autoGenerated
        ]
    }

    private enum ClipboardPayload: Sendable {
        case text(String, String?, String?, [ClipboardRepresentation])
        case url(String, String?, String?, [ClipboardRepresentation])
        case file(String, String?, String?, [ClipboardRepresentation])
        /// 图片数据延迟到 detached task 内通过 MainActor.run 拉取：避免 500ms timer 主线程
        /// 同步读 TIFF（截图原图可数 MB）卡 UI；用 captured changeCount 防止读到下一次复制的数据。
        /// 辅助 reps（file-url/html/url 等）也在后台 hop 主线程时一起读，保持单次 pasteboard 快照一致性。
        case imageLazy(changeCount: Int, sourceApp: String?, sourceName: String?)
    }

    private let core: ClipinCore
    private let settings: SettingsStore
    private var timer: Timer?
    private var lastChangeCount: Int
    private var isPaused = false
    /// 持有所有正在跑的 persist task，stop() 时统一取消。
    /// 旧实现 Task.detached 启动后没有持有引用，监控停止/进程退出时正在跑的图片 OCR
    /// 仍会继续 Vision 调用并发通知，破坏 launcher 关闭后"什么都不再变"的语义。
    /// 取消不会 abort 已经开始的 SQLite write，但 OCR 段（recognizeText）会响应。
    private var inflightPersists: Set<Task<Void, Never>> = []

    init(core: ClipinCore, settings: SettingsStore) {
        self.core = core
        self.settings = settings
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        guard timer == nil else { return }
        timer = Timer.scheduledTimer(withTimeInterval: Self.pollingInterval, repeats: true) { [weak self] _ in
            Task { @MainActor in
                self?.checkClipboard()
            }
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        let pending = inflightPersists
        inflightPersists.removeAll()
        pending.forEach { $0.cancel() }
    }

    /// 暂停监控（粘贴时用，避免把自己写入的内容又存一遍）
    func pause() {
        isPaused = true
    }

    /// 恢复监控，跳过暂停期间的变化
    func resume() {
        lastChangeCount = NSPasteboard.general.changeCount
        isPaused = false
    }

    var onNewItem: (() -> Void)?

    private func checkClipboard() {
        guard !isPaused else { return }

        let pasteboard = NSPasteboard.general
        let currentCount = pasteboard.changeCount
        guard currentCount != lastChangeCount else { return }
        lastChangeCount = currentCount

        guard shouldPersistContents(of: pasteboard) else { return }

        let source = resolveSourceApp(from: pasteboard)
        let sourceApp = source.bundleIdentifier
        let sourceName = source.appName

        // 判定顺序：image → file → url → text
        // image 必须优先于 file：iPhone 隔空剪贴板复制图片时，pasteboard 同时挂载
        // file-url（指向 useractivityd 临时文件，会被系统清理）+ image bytes。
        // 让 file 抢走会让"翻历史回放"在临时文件清理后死掉。Clipin 是历史型应用，
        // 语义上"翻历史的图"应该是图片数据而不是磁盘文件引用；损失"Finder 间复制
        // 图片文件经 Clipin 回放为文件粘贴"的边角场景，换主流图片场景可靠。
        if Self.hasImageData(in: pasteboard) {
            // 不在这里同步读数据：types 探测廉价，timer 立即返回；data 由后台任务通过
            // MainActor.run 拉，主线程读取还在但不再占用 timer 触发那一帧
            persist(.imageLazy(changeCount: currentCount, sourceApp: sourceApp, sourceName: sourceName))
        } else if let fileURLs = pasteboard.readObjects(forClasses: [NSURL.self], options: [
            .urlReadingFileURLsOnly: true
        ]) as? [URL], !fileURLs.isEmpty {
            let paths = fileURLs.map(\.path)
            // 辅助 reps：file 类型可能附带 image data（系统给的预览/缩略图）、HTML、URL 等；
            // 粘到富文本编辑器能消费 image data 显示图，而不是裸路径字符串
            let reps = ClipboardRepresentationExtractor.extractAuxiliary(from: pasteboard, primaryClipType: .file)
            persist(.file(FileClipboardContent.encodedContent(from: paths), sourceApp, sourceName, reps))
        } else if let urlString = pasteboard.string(forType: .URL) ?? extractURL(from: pasteboard) {
            let reps = ClipboardRepresentationExtractor.extract(from: pasteboard, primaryContent: urlString)
            persist(.url(urlString, sourceApp, sourceName, reps))
        } else if let text = pasteboard.string(forType: .string), !text.isEmpty {
            // 超大文本（终端 dump、整本电子书等）跳过：FTS 重建会卡，磁盘也会被吃光
            if text.utf8.count > Self.maxTextBytes {
                ClipinLog.monitor.notice("Skipped clipboard text larger than \(Self.maxTextBytes, privacy: .public) bytes")
                return
            }
            let reps = ClipboardRepresentationExtractor.extract(from: pasteboard, primaryContent: text)
            persist(.text(text, sourceApp, sourceName, reps))
        }
    }

    private func persist(_ payload: ClipboardPayload) {
        let core = self.core

        // 自引用 box：task body 完成时回主线程从 inflightPersists 移除自己，避免集合无限增长。
        // 用 Box<Task?> 是因为 Task 创建时还没拿到自身引用——先建 box、Task 内闭包持有 box、
        // Task 创建后写入 box，闭包 defer 时通过 box 拿到 task 引用。
        let box = TaskBox()
        let task = Task.detached(priority: .utility) { [weak self] in
            defer {
                // 显式把 weak self 重新 capture 进 inner Task：Swift 6 严格 isolation 下
                // 直接在 detached body 的 defer 里捕获外层 weak self 会被判为跨 actor
                // 边界 send 引用（即使 Monitor 是 @MainActor 也不行）。重 capture 后就是
                // 一次普通的 MainActor 任务调度。
                let monitor = self
                Task { @MainActor in
                    guard let task = box.task else { return }
                    monitor?.inflightPersists.remove(task)
                }
            }
            do {
                switch payload {
                case let .text(content, sourceApp, sourceName, reps):
                    let coreReps = reps.map { ClipRepresentation(uti: $0.uti, data: $0.data) }
                    _ = try core.saveItemWithRepresentations(
                        content: content,
                        clipType: .text,
                        sourceApp: sourceApp,
                        sourceName: sourceName,
                        imagePath: nil,
                        representations: coreReps
                    )

                case let .url(content, sourceApp, sourceName, reps):
                    let coreReps = reps.map { ClipRepresentation(uti: $0.uti, data: $0.data) }
                    _ = try core.saveItemWithRepresentations(
                        content: content,
                        clipType: .url,
                        sourceApp: sourceApp,
                        sourceName: sourceName,
                        imagePath: nil,
                        representations: coreReps
                    )

                case let .file(path, sourceApp, sourceName, reps):
                    let coreReps = reps.map { ClipRepresentation(uti: $0.uti, data: $0.data) }
                    _ = try core.saveItemWithRepresentations(
                        content: path,
                        clipType: .file,
                        sourceApp: sourceApp,
                        sourceName: sourceName,
                        imagePath: nil,
                        representations: coreReps
                    )

                case let .imageLazy(capturedChangeCount, sourceApp, sourceName):
                    // 后台任务里 hop 回 main 拉 pasteboard data + 辅助 reps：
                    // 必须在单次 hop 内一起读，确保 image bytes 和 file-url/html 等
                    // 都来自同一个 pasteboard 快照，否则中间用户又复制别的会割裂
                    struct ImageSnapshot { let data: Data; let reps: [ClipboardRepresentation] }
                    let snapshot: ImageSnapshot? = await MainActor.run {
                        let pb = NSPasteboard.general
                        // 用户已经又复制了别的内容，捕获到的快照已过期，丢弃
                        guard pb.changeCount == capturedChangeCount else { return nil }
                        guard let imageData = Self.readImageData(from: pb) else { return nil }
                        let auxReps = ClipboardRepresentationExtractor.extractAuxiliary(from: pb, primaryClipType: .image)
                        return ImageSnapshot(data: imageData, reps: auxReps)
                    }
                    guard let snapshot else { return }
                    if Task.isCancelled { return }
                    let imageDir = core.imageDir()
                    let filename = UUID().uuidString + ".png"
                    let path = (imageDir as NSString).appendingPathComponent(filename)
                    let pngData = try Self.makePNGData(from: snapshot.data)
                    try pngData.write(to: URL(fileURLWithPath: path), options: .atomic)
                    let coreReps = snapshot.reps.map { ClipRepresentation(uti: $0.uti, data: $0.data) }
                    let saved = try core.saveItemWithRepresentations(
                        content: "image",
                        clipType: .image,
                        sourceApp: sourceApp,
                        sourceName: sourceName,
                        imagePath: path,
                        representations: coreReps
                    )
                    // 入库后立即读图片头写回尺寸，让列表首次渲染就带 (宽×高)。
                    // 读尺寸失败不阻断采集（fire-and-forget），历史 backfill 会再补。
                    if let size = ImageDimensions.read(at: path) {
                        do {
                            try core.updateImageDimensions(
                                id: saved.id, width: size.width, height: size.height)
                        } catch {
                            ClipinLog.imageDimensions.error("图片尺寸写入失败 id=\(saved.id, privacy: .public): \(error.localizedDescription, privacy: .public)")
                        }
                    }
                    // 图片入库后立即刷新列表，让条目即时出现，不等 OCR
                    guard let self else { return }
                    await self.notifyNewItem()

                    // stop() 取消后，DB 已经写完不能撤销，但 OCR/通知都跳过，
                    // 避免 launcher 关闭后还冒出"OCR 完成"广播。
                    if Task.isCancelled { return }

                    // OCR 在同一后台 Task 内串行执行，完成后二次刷新显示文字
                    // 无论是否识别到文字都写回（NULL=未处理，""=处理过但无文字，避免重复 backfill）
                    let itemId = saved.id
                    let ocrText = await OcrService.recognizeText(at: path)
                    if Task.isCancelled { return }
                    do {
                        try core.updateOcrText(id: itemId, ocrText: ocrText)
                        if !ocrText.isEmpty {
                            NotificationCenter.default.post(name: .clipboardItemOcrUpdated, object: nil)
                        }
                    } catch {
                        if case ClipinError.NotFound = error {
                            // 图片在 OCR 期间被去重替换（连续复制同一图片），OCR 结果丢弃是预期行为
                            ClipinLog.ocr.info("OCR result discarded: item \(itemId, privacy: .public) was replaced by dedup")
                        } else {
                            ClipinLog.ocr.error("Failed to write OCR result id=\(itemId, privacy: .public): \(error.localizedDescription, privacy: .public)")
                        }
                    }
                    return  // image case 已自行通知，跳过下方公共 notifyNewItem
                }

                guard let self else { return }
                await self.notifyNewItem()
            } catch {
                ClipinLog.monitor.error("Failed to persist clipboard item: \(error.localizedDescription, privacy: .public)")
            }
        }
        box.task = task
        inflightPersists.insert(task)
    }

    private func shouldPersistContents(of pasteboard: NSPasteboard) -> Bool {
        let types = Set(pasteboard.types ?? [])

        // ConcealedType：密码管理器等明确标记的敏感内容，始终跳过
        if types.contains(PasteboardMetadata.concealed) {
            settings.incrementNoiseSkipped()
            return false
        }

        // TransientType / AutoGeneratedType：临时或自动生成内容，由用户设置决定
        if settings.skipTransientContent {
            let transientTypes: Set<NSPasteboard.PasteboardType> = [
                PasteboardMetadata.transient,
                PasteboardMetadata.autoGenerated,
            ]
            if !types.isDisjoint(with: transientTypes) {
                settings.incrementNoiseSkipped()
                return false
            }
        }

        // Clipin 自己写回的剪贴板内容（粘贴回写）不计入"噪声"，是预期回路
        if let sourceBundleID = pasteboard.string(forType: PasteboardMetadata.sourceBundleID),
           sourceBundleID == Bundle.main.bundleIdentifier {
            return false
        }

        return true
    }

    private func resolveSourceApp(from pasteboard: NSPasteboard) -> (bundleIdentifier: String?, appName: String?) {
        if let bundleIdentifier = pasteboard.string(forType: PasteboardMetadata.sourceBundleID),
           !bundleIdentifier.isEmpty {
            let appName = NSRunningApplication
                .runningApplications(withBundleIdentifier: bundleIdentifier)
                .first?
                .localizedName
            return (bundleIdentifier, appName)
        }

        let tracker = SourceAppTracker.shared
        return (tracker.bundleIdentifier, tracker.appName)
    }

    /// 判断一段文本是否为 http/https URL。是则原样返回（保留大小写与参数），否则 nil。
    /// Edit Content 保存时复用此判据，确保与剪贴板监控的 URL 识别口径一致。
    /// `nonisolated`：纯函数无 actor 状态，需同时被 @MainActor 的 ViewModel 与
    /// nonisolated 的单元测试调用——与下方 `makePNGData` 同一惯例。
    nonisolated static func httpURLString(in text: String) -> String? {
        guard let url = URL(string: text),
              let scheme = url.scheme,
              ["http", "https"].contains(scheme) else { return nil }
        return text
    }

    private func extractURL(from pasteboard: NSPasteboard) -> String? {
        guard let text = pasteboard.string(forType: .string) else { return nil }
        return Self.httpURLString(in: text)
    }

    /// 判定 pasteboard 是否含有"图片数据"。
    /// 旧实现只白名单 .tiff / .png，漏掉 iPhone 隔空剪贴板复制 jpeg 时挂的 public.jpeg
    /// （也漏 heic/heif/gif/webp/bmp 等所有非 PNG/TIFF 格式）。
    /// 现改为 UTType conformance 动态判定：任何 conforms to public.image 的 UTI 都算图片。
    /// 显式排除 public.file-url：它自身不 conforms to image，但保险起见排除，
    /// 避免未来 macOS 给 file-url 加 image conformance 时让"file 复制"误入 image 分支。
    nonisolated private static func hasImageData(in pasteboard: NSPasteboard) -> Bool {
        guard let types = pasteboard.types else { return false }
        return types.contains(where: { Self.isImageContentType($0) })
    }

    /// 从 pasteboard 读出任意 image UTI 的原始 bytes。
    /// PNG/TIFF 优先（macOS 原生格式，无需重编码就能落地），其他格式（jpeg/heic/gif/webp 等）
    /// 兜底——makePNGData 用 CGImageSource 统一转 PNG，所有 ImageIO 支持的格式都能跑。
    nonisolated private static func readImageData(from pasteboard: NSPasteboard) -> Data? {
        let preferred: [NSPasteboard.PasteboardType] = [.png, .tiff]
        let availableTypes = Set(pasteboard.types ?? [])
        for type in preferred where availableTypes.contains(type) {
            if let data = pasteboard.data(forType: type) { return data }
        }
        for type in pasteboard.types ?? [] where Self.isImageContentType(type) {
            if let data = pasteboard.data(forType: type) { return data }
        }
        return nil
    }

    /// 判定单个 UTI 是否表示"图片内容"。public.file-url 显式排除（理由见 hasImageData 注释）。
    nonisolated private static func isImageContentType(_ type: NSPasteboard.PasteboardType) -> Bool {
        guard type.rawValue != "public.file-url" else { return false }
        guard let utType = UTType(type.rawValue) else { return false }
        return utType.conforms(to: .image)
    }

    nonisolated private static func makePNGData(from data: Data) throws -> Data {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil),
              let image = CGImageSourceCreateImageAtIndex(source, 0, nil) else {
            throw ClipboardMonitorError.invalidImageData
        }

        let output = NSMutableData()
        guard let destination = CGImageDestinationCreateWithData(
            output,
            UTType.png.identifier as CFString,
            1,
            nil
        ) else {
            throw ClipboardMonitorError.failedToEncodePNG
        }

        CGImageDestinationAddImage(destination, image, nil)
        guard CGImageDestinationFinalize(destination) else {
            throw ClipboardMonitorError.failedToEncodePNG
        }

        return output as Data
    }

    @MainActor
    private func notifyNewItem() {
        NotificationCenter.default.post(name: .clipHistoryItemSaved, object: nil)
        onNewItem?()
    }
}

private enum ClipboardMonitorError: Error {
    case invalidImageData
    case failedToEncodePNG
}

/// 给 Task body 一个延迟回填 task 引用的容器：Task 创建时拿不到自己的 handle，
/// 但 body defer 时需要它来从 inflightPersists 移除——typed box 避开循环引用陷阱。
@MainActor
private final class TaskBox {
    var task: Task<Void, Never>?
}
