import Combine
import Foundation
import ServiceManagement

enum AppLanguage: String, CaseIterable {
    case system       = "system"
    case english      = "en"
    case simplifiedCN = "zh-Hans"

    var displayName: String {
        switch self {
        case .system:       return NSLocalizedString("System Default", comment: "")
        case .english:      return "English"
        case .simplifiedCN: return "简体中文"
        }
    }

    /// AppleLanguages 数组的实际值，nil 表示删除 key（跟随系统）
    var appleLanguagesValue: [String]? {
        switch self {
        case .system:       return nil
        case .english:      return ["en"]
        case .simplifiedCN: return ["zh-Hans"]
        }
    }
}

enum AppearanceOverride: String, CaseIterable {
    case system = "system"
    case light  = "light"
    case dark   = "dark"

    var displayName: String {
        switch self {
        case .system: return NSLocalizedString("System", comment: "")
        case .light:  return NSLocalizedString("Light", comment: "")
        case .dark:   return NSLocalizedString("Dark", comment: "")
        }
    }
}

@MainActor
final class SettingsStore: ObservableObject {
    static let shared = SettingsStore()

    @Published var retentionDays: Int {
        didSet {
            // 0 = 永久保留，否则最少 1 天
            let clamped = retentionDays <= 0 ? 0 : max(1, retentionDays)
            guard retentionDays == clamped else {
                retentionDays = clamped
                return
            }
            defaults.set(clamped, forKey: Keys.retentionDays)
        }
    }

    @Published var maxHistoryItems: Int {
        didSet {
            // 0 = 不限数量，否则最少 50
            let clamped = maxHistoryItems <= 0 ? 0 : max(50, maxHistoryItems)
            guard maxHistoryItems == clamped else {
                maxHistoryItems = clamped
                return
            }
            defaults.set(clamped, forKey: Keys.maxHistoryItems)
        }
    }

    @Published var shortcut: HotKeyShortcut {
        didSet {
            guard let data = try? encoder.encode(shortcut) else { return }
            defaults.set(data, forKey: Keys.shortcut)
        }
    }

    /// 是否跳过 TransientType / AutoGeneratedType 的剪贴板内容（降噪）。
    /// 注意：ConcealedType（密码管理器）始终跳过，不受此开关影响。
    @Published var skipTransientContent: Bool {
        didSet { defaults.set(skipTransientContent, forKey: Keys.skipTransientContent) }
    }

    @Published var autoBackupEnabled: Bool {
        didSet { defaults.set(autoBackupEnabled, forKey: Keys.autoBackupEnabled) }
    }

    /// 用户选择的备份文件夹绝对路径，nil 表示未配置
    @Published var autoBackupFolderPath: String? {
        didSet { defaults.set(autoBackupFolderPath, forKey: Keys.autoBackupFolderPath) }
    }

    @Published var autoBackupInterval: AutoBackupInterval {
        didSet { defaults.set(autoBackupInterval.rawValue, forKey: Keys.autoBackupInterval) }
    }

    @Published var appearanceOverride: AppearanceOverride {
        didSet { defaults.set(appearanceOverride.rawValue, forKey: Keys.appearanceOverride) }
    }

    @Published var visualTheme: VisualTheme {
        didSet { defaults.set(visualTheme.rawValue, forKey: Keys.visualTheme) }
    }

    @Published var appLanguage: AppLanguage {
        didSet {
            if let langs = appLanguage.appleLanguagesValue {
                defaults.set(langs, forKey: "AppleLanguages")
            } else {
                defaults.removeObject(forKey: "AppleLanguages")
            }
            defaults.set(appLanguage.rawValue, forKey: Keys.appLanguage)
        }
    }

    @Published private(set) var launchAtLoginEnabled = false
    @Published private(set) var launchAtLoginNote: String?

    private let defaults = UserDefaults.standard
    private let encoder = JSONEncoder()

    private enum Keys {
        static let retentionDays = "settings.retentionDays"
        static let maxHistoryItems = "settings.maxHistoryItems"
        static let shortcut = "settings.shortcut"
        static let skipTransientContent = "settings.skipTransientContent"
        static let autoBackupEnabled = "settings.autoBackupEnabled"
        static let autoBackupFolderPath = "settings.autoBackupFolderPath"
        static let autoBackupInterval = "settings.autoBackupInterval"
        static let appearanceOverride = "settings.appearanceOverride"
        static let visualTheme = "settings.visualTheme"
        static let appLanguage = "settings.appLanguage"
    }

    private init() {
        let decoder = JSONDecoder()
        let storedRetention = defaults.object(forKey: Keys.retentionDays) as? Int ?? 30
        let storedMaxItems = defaults.object(forKey: Keys.maxHistoryItems) as? Int ?? 500
        let storedShortcut = defaults.data(forKey: Keys.shortcut)
            .flatMap { try? decoder.decode(HotKeyShortcut.self, from: $0) }
            ?? .default
        let storedInterval = defaults.string(forKey: Keys.autoBackupInterval)
            .flatMap { AutoBackupInterval(rawValue: $0) } ?? .weekly
        let storedAppearance = defaults.string(forKey: Keys.appearanceOverride)
            .flatMap { AppearanceOverride(rawValue: $0) } ?? .system
        let storedVisualTheme = defaults.string(forKey: Keys.visualTheme)
            .flatMap { VisualTheme(rawValue: $0) } ?? .mist
        let storedAppLanguage = defaults.string(forKey: Keys.appLanguage)
            .flatMap { AppLanguage(rawValue: $0) } ?? .system

        self.retentionDays = storedRetention
        self.maxHistoryItems = storedMaxItems
        self.shortcut = storedShortcut
        self.skipTransientContent = defaults.object(forKey: Keys.skipTransientContent) as? Bool ?? false
        self.autoBackupEnabled = defaults.bool(forKey: Keys.autoBackupEnabled)
        self.autoBackupFolderPath = defaults.string(forKey: Keys.autoBackupFolderPath)
        self.autoBackupInterval = storedInterval
        self.appearanceOverride = storedAppearance
        self.visualTheme = storedVisualTheme
        self.appLanguage = storedAppLanguage
        refreshLaunchAtLoginStatus()
    }

    func refreshLaunchAtLoginStatus() {
        let status = SMAppService.mainApp.status
        switch status {
        case .enabled:
            launchAtLoginEnabled = true
            launchAtLoginNote = NSLocalizedString("Clipin will start automatically after you log in.", comment: "")
        case .requiresApproval:
            launchAtLoginEnabled = false
            launchAtLoginNote = NSLocalizedString("Login launch is pending approval in System Settings.", comment: "")
        default:
            launchAtLoginEnabled = false
            launchAtLoginNote = nil
        }
    }

    func setLaunchAtLogin(_ enabled: Bool) {
        do {
            let service = SMAppService.mainApp
            if enabled {
                try service.register()
            } else {
                try service.unregister()
            }
            refreshLaunchAtLoginStatus()
        } catch {
            refreshLaunchAtLoginStatus()
            launchAtLoginNote = error.localizedDescription
        }
    }
}

enum AutoBackupInterval: String, CaseIterable {
    case onChange = "onChange"
    case daily    = "daily"
    case weekly   = "weekly"
    case monthly  = "monthly"

    var displayName: String {
        switch self {
        case .onChange: return NSLocalizedString("On Clipboard Change", comment: "")
        case .daily:    return NSLocalizedString("Daily", comment: "")
        case .weekly:   return NSLocalizedString("Weekly", comment: "")
        case .monthly:  return NSLocalizedString("Monthly", comment: "")
        }
    }

    /// 两次备份之间的最小间隔。nil = onChange 触发型，不使用定时器
    var backupInterval: TimeInterval? {
        switch self {
        case .onChange: return nil
        case .daily:    return 24 * 60 * 60
        case .weekly:   return 7 * 24 * 60 * 60
        case .monthly:  return 30 * 24 * 60 * 60
        }
    }

    /// 定时检查"是否逾期"的轮询间隔，远小于 backupInterval 以保证不漏触发
    var checkInterval: TimeInterval? {
        switch self {
        case .onChange: return nil
        case .daily:    return 60 * 60          // 每小时检查
        case .weekly:   return 6 * 60 * 60      // 每 6 小时检查
        case .monthly:  return 24 * 60 * 60     // 每天检查
        }
    }
}
