import Combine
import Foundation
import ServiceManagement

enum AppLanguage: String, CaseIterable {
    case system       = "system"
    case english      = "en"
    case simplifiedCN = "zh-Hans"

    var displayName: String {
        switch self {
        case .system:       return NSLocalizedString("System Default", comment: "")
        case .english:      return NSLocalizedString("English", comment: "")
        case .simplifiedCN: return "简体中文"
        }
    }

    /// AppleLanguages 数组的实际值，nil 表示删除 key（跟随系统）
    var appleLanguagesValue: [String]? {
        switch self {
        case .system:       return nil
        case .english:      return ["en"]
        case .simplifiedCN: return ["zh-Hans"]
        }
    }
}

enum AppearanceOverride: String, CaseIterable {
    case system = "system"
    case light  = "light"
    case dark   = "dark"

    var displayName: String {
        switch self {
        case .system: return NSLocalizedString("System", comment: "")
        case .light:  return NSLocalizedString("Light", comment: "")
        case .dark:   return NSLocalizedString("Dark", comment: "")
        }
    }
}

enum LauncherBrowseMode: String, CaseIterable {
    case all
    case pinned
    case text
    case image
    case file
    case url

    var displayName: String {
        switch self {
        case .all:
            return NSLocalizedString("All Items", comment: "")
        case .pinned:
            return NSLocalizedString("Pinned Items", comment: "")
        case .text:
            return NSLocalizedString("Text", comment: "")
        case .image:
            return NSLocalizedString("Images", comment: "")
        case .file:
            return NSLocalizedString("Files", comment: "")
        case .url:
            return NSLocalizedString("URLs", comment: "")
        }
    }

    var typeFilter: ClipType? {
        switch self {
        case .all, .pinned:
            return nil
        case .text:
            return .text
        case .image:
            return .image
        case .file:
            return .file
        case .url:
            return .url
        }
    }

    var isPinnedOnly: Bool { self == .pinned }

    init(typeFilter: ClipType?) {
        switch typeFilter {
        case .text:
            self = .text
        case .image:
            self = .image
        case .file:
            self = .file
        case .url:
            self = .url
        case nil:
            self = .all
        @unknown default:
            self = .all
        }
    }
}

enum PinnedItemsPresentation: String, CaseIterable {
    case mixed
    case topSection
    case pinnedOnlyView

    var displayName: String {
        switch self {
        case .mixed:
            return NSLocalizedString("Mixed with recent items", comment: "")
        case .topSection:
            return NSLocalizedString("Separate pinned section", comment: "")
        case .pinnedOnlyView:
            return NSLocalizedString("Only in pinned view", comment: "")
        }
    }
}

enum LauncherDefaultView: String, CaseIterable {
    case allItems
    case pinnedItems
    case rememberLastView

    var displayName: String {
        switch self {
        case .allItems:
            return NSLocalizedString("All Items", comment: "")
        case .pinnedItems:
            return NSLocalizedString("Pinned Items", comment: "")
        case .rememberLastView:
            return NSLocalizedString("Remember Last View", comment: "")
        }
    }
}

@MainActor
final class SettingsStore: ObservableObject {
    static let shared = SettingsStore()
    private static let currentOnboardingVersion = 1

    private enum OnboardingCohort: String {
        case newInstall
        case legacyInstall
    }

    @Published var retentionDays: Int {
        didSet {
            // 0 = 永久保留，否则最少 1 天
            let clamped = retentionDays <= 0 ? 0 : max(1, retentionDays)
            guard retentionDays == clamped else {
                retentionDays = clamped
                return
            }
            defaults.set(clamped, forKey: Keys.retentionDays)
        }
    }

    @Published var maxHistoryItems: Int {
        didSet {
            // 0 = 不限数量，否则最少 50
            let clamped = maxHistoryItems <= 0 ? 0 : max(50, maxHistoryItems)
            guard maxHistoryItems == clamped else {
                maxHistoryItems = clamped
                return
            }
            defaults.set(clamped, forKey: Keys.maxHistoryItems)
        }
    }

    @Published var shortcut: HotKeyShortcut {
        didSet {
            guard let data = try? encoder.encode(shortcut) else { return }
            defaults.set(data, forKey: Keys.shortcut)
        }
    }

    /// 是否跳过 TransientType / AutoGeneratedType 的剪贴板内容（降噪）。
    /// 注意：ConcealedType（密码管理器）始终跳过，不受此开关影响。
    @Published var skipTransientContent: Bool {
        didSet { defaults.set(skipTransientContent, forKey: Keys.skipTransientContent) }
    }

    @Published var autoBackupEnabled: Bool {
        didSet { defaults.set(autoBackupEnabled, forKey: Keys.autoBackupEnabled) }
    }

    /// 用户选择的备份文件夹绝对路径，nil 表示未配置
    @Published var autoBackupFolderPath: String? {
        didSet { defaults.set(autoBackupFolderPath, forKey: Keys.autoBackupFolderPath) }
    }

    @Published var autoBackupInterval: AutoBackupInterval {
        didSet { defaults.set(autoBackupInterval.rawValue, forKey: Keys.autoBackupInterval) }
    }

    @Published var appearanceOverride: AppearanceOverride {
        didSet { defaults.set(appearanceOverride.rawValue, forKey: Keys.appearanceOverride) }
    }

    @Published var visualTheme: VisualTheme {
        didSet { defaults.set(visualTheme.rawValue, forKey: Keys.visualTheme) }
    }

    @Published var appLanguage: AppLanguage {
        didSet {
            if let langs = appLanguage.appleLanguagesValue {
                defaults.set(langs, forKey: "AppleLanguages")
            } else {
                defaults.removeObject(forKey: "AppleLanguages")
            }
            defaults.set(appLanguage.rawValue, forKey: Keys.appLanguage)
        }
    }

    @Published var rememberPanelPosition: Bool {
        didSet { defaults.set(rememberPanelPosition, forKey: Keys.rememberPanelPosition) }
    }

    @Published var pinnedItemsPresentation: PinnedItemsPresentation {
        didSet { defaults.set(pinnedItemsPresentation.rawValue, forKey: Keys.pinnedItemsPresentation) }
    }

    @Published var launcherDefaultView: LauncherDefaultView {
        didSet { defaults.set(launcherDefaultView.rawValue, forKey: Keys.launcherDefaultView) }
    }

    @Published private(set) var lastLauncherBrowseMode: LauncherBrowseMode {
        didSet { defaults.set(lastLauncherBrowseMode.rawValue, forKey: Keys.lastLauncherBrowseMode) }
    }

    @Published var floatingNoteShortcut: HotKeyShortcut {
        didSet {
            guard let data = try? encoder.encode(floatingNoteShortcut) else { return }
            defaults.set(data, forKey: Keys.floatingNoteShortcut)
        }
    }

    /// 浮动笔记的根目录绝对路径，nil 表示未配置
    @Published var floatingNoteRootFolder: String? {
        didSet { defaults.set(floatingNoteRootFolder, forKey: Keys.floatingNoteRootFolder) }
    }

    /// 文件命名规则，支持 YYYY MM DD HH WW 占位符，或固定文件名（如 inbox.md）
    @Published var floatingNotePattern: String {
        didSet { defaults.set(floatingNotePattern, forKey: Keys.floatingNotePattern) }
    }

    /// 新文件的默认模板内容，空串表示不预填
    @Published var floatingNoteTemplate: String {
        didSet { defaults.set(floatingNoteTemplate, forKey: Keys.floatingNoteTemplate) }
    }

    @Published private(set) var launchAtLoginEnabled = false
    @Published private(set) var launchAtLoginNote: String?

    /// 首次引导版本。用版本号而不是 Bool，后续若需要重做 onboarding 可平滑升级。
    private(set) var onboardingVersion: Int
    /// 首次看到 onboarding 功能时的安装归类。
    /// 只在第一次判定时计算一次，避免真正的新用户因为首启已创建本地存储而在下次启动被误判成老用户。
    private var onboardingCohort: OnboardingCohort?

    private let defaults = UserDefaults.standard
    private let encoder = JSONEncoder()

    private enum Keys {
        static let retentionDays = "settings.retentionDays"
        static let maxHistoryItems = "settings.maxHistoryItems"
        static let shortcut = "settings.shortcut"
        static let skipTransientContent = "settings.skipTransientContent"
        static let autoBackupEnabled = "settings.autoBackupEnabled"
        static let autoBackupFolderPath = "settings.autoBackupFolderPath"
        static let autoBackupInterval = "settings.autoBackupInterval"
        static let appearanceOverride = "settings.appearanceOverride"
        static let visualTheme = "settings.visualTheme"
        static let appLanguage = "settings.appLanguage"
        static let rememberPanelPosition = "settings.rememberPanelPosition"
        static let pinnedItemsPresentation = "settings.pinnedItemsPresentation"
        static let launcherDefaultView = "settings.launcherDefaultView"
        static let lastLauncherBrowseMode = "settings.lastLauncherBrowseMode"
        static let onboardingVersion = "settings.onboardingVersion"
        static let onboardingCohort = "settings.onboardingCohort"
        static let floatingNoteShortcut = "settings.floatingNoteShortcut"
        static let floatingNoteRootFolder = "settings.floatingNoteRootFolder"
        static let floatingNotePattern = "settings.floatingNotePattern"
        static let floatingNoteTemplate = "settings.floatingNoteTemplate"
    }

    /// 老用户迁移信号：任意一个 key 已存在，就说明这个安装已经被实际使用过，不应突然弹欢迎页。
    private static let legacyInstallKeys: [String] = [
        Keys.retentionDays,
        Keys.maxHistoryItems,
        Keys.shortcut,
        Keys.skipTransientContent,
        Keys.autoBackupEnabled,
        Keys.autoBackupFolderPath,
        Keys.autoBackupInterval,
            Keys.appearanceOverride,
            Keys.visualTheme,
            Keys.appLanguage,
            Keys.rememberPanelPosition,
            Keys.pinnedItemsPresentation,
            Keys.launcherDefaultView,
            Keys.lastLauncherBrowseMode,
            "panel.savedOriginX",
            "panel.savedOriginY",
            "autoBackup.lastBackupAt",
    ]

    private init() {
        let decoder = JSONDecoder()
        let storedRetention = defaults.object(forKey: Keys.retentionDays) as? Int ?? 30
        let storedMaxItems = defaults.object(forKey: Keys.maxHistoryItems) as? Int ?? 500
        let storedShortcut = defaults.data(forKey: Keys.shortcut)
            .flatMap { try? decoder.decode(HotKeyShortcut.self, from: $0) }
            ?? .default
        let storedFloatingNoteShortcut = defaults.data(forKey: Keys.floatingNoteShortcut)
            .flatMap { try? decoder.decode(HotKeyShortcut.self, from: $0) }
            ?? .defaultFloatingNote
        let storedInterval = defaults.string(forKey: Keys.autoBackupInterval)
            .flatMap { AutoBackupInterval(rawValue: $0) } ?? .weekly
        let storedAppearance = defaults.string(forKey: Keys.appearanceOverride)
            .flatMap { AppearanceOverride(rawValue: $0) } ?? .system
        let storedVisualTheme = defaults.string(forKey: Keys.visualTheme)
            .flatMap { VisualTheme(rawValue: $0) } ?? .mist
        let storedAppLanguage = defaults.string(forKey: Keys.appLanguage)
            .flatMap { AppLanguage(rawValue: $0) } ?? .system
        let storedPinnedItemsPresentation = defaults.string(forKey: Keys.pinnedItemsPresentation)
            .flatMap { PinnedItemsPresentation(rawValue: $0) } ?? .mixed
        let storedLauncherDefaultView = defaults.string(forKey: Keys.launcherDefaultView)
            .flatMap { LauncherDefaultView(rawValue: $0) } ?? .allItems
        let storedLastLauncherBrowseMode = defaults.string(forKey: Keys.lastLauncherBrowseMode)
            .flatMap { LauncherBrowseMode(rawValue: $0) } ?? .all
        let storedOnboardingVersion = defaults.object(forKey: Keys.onboardingVersion) as? Int ?? 0
        let storedOnboardingCohort = defaults.string(forKey: Keys.onboardingCohort)
            .flatMap { OnboardingCohort(rawValue: $0) }

        self.retentionDays = storedRetention
        self.maxHistoryItems = storedMaxItems
        self.shortcut = storedShortcut
        self.floatingNoteShortcut = storedFloatingNoteShortcut
        self.floatingNoteRootFolder = defaults.string(forKey: Keys.floatingNoteRootFolder)
        self.floatingNotePattern = defaults.string(forKey: Keys.floatingNotePattern) ?? "YYYY-MM-DD.md"
        self.floatingNoteTemplate = defaults.string(forKey: Keys.floatingNoteTemplate) ?? ""
        self.skipTransientContent = defaults.object(forKey: Keys.skipTransientContent) as? Bool ?? false
        self.autoBackupEnabled = defaults.bool(forKey: Keys.autoBackupEnabled)
        self.autoBackupFolderPath = defaults.string(forKey: Keys.autoBackupFolderPath)
        self.autoBackupInterval = storedInterval
        self.appearanceOverride = storedAppearance
        self.visualTheme = storedVisualTheme
        self.appLanguage = storedAppLanguage
        self.rememberPanelPosition = defaults.object(forKey: Keys.rememberPanelPosition) as? Bool ?? false
        self.pinnedItemsPresentation = storedPinnedItemsPresentation
        self.launcherDefaultView = storedLauncherDefaultView
        self.lastLauncherBrowseMode = storedLastLauncherBrowseMode
        self.onboardingVersion = storedOnboardingVersion
        self.onboardingCohort = storedOnboardingCohort
        // init 赋值不触发 didSet，需手动同步确保 AppleLanguages 和持久化值一致
        if let langs = storedAppLanguage.appleLanguagesValue {
            defaults.set(langs, forKey: "AppleLanguages")
        } else {
            defaults.removeObject(forKey: "AppleLanguages")
        }
        refreshLaunchAtLoginStatus()
    }

    func refreshLaunchAtLoginStatus() {
        let status = SMAppService.mainApp.status
        switch status {
        case .enabled:
            launchAtLoginEnabled = true
            launchAtLoginNote = NSLocalizedString("Clipin will start automatically after you log in.", comment: "")
        case .requiresApproval:
            launchAtLoginEnabled = false
            launchAtLoginNote = NSLocalizedString("Login launch is pending approval in System Settings.", comment: "")
        default:
            launchAtLoginEnabled = false
            launchAtLoginNote = nil
        }
    }

    func resolvedLaunchBrowseMode() -> LauncherBrowseMode {
        switch launcherDefaultView {
        case .allItems:
            return .all
        case .pinnedItems:
            return .pinned
        case .rememberLastView:
            return lastLauncherBrowseMode
        }
    }

    func recordLastLauncherBrowseMode(_ mode: LauncherBrowseMode) {
        lastLauncherBrowseMode = mode
    }

    func setLaunchAtLogin(_ enabled: Bool) {
        do {
            let service = SMAppService.mainApp
            if enabled {
                try service.register()
            } else {
                try service.unregister()
            }
            refreshLaunchAtLoginStatus()
        } catch {
            refreshLaunchAtLoginStatus()
            launchAtLoginNote = error.localizedDescription
        }
    }

    var hasCompletedOnboarding: Bool {
        onboardingVersion >= Self.currentOnboardingVersion
    }

    /// 只对真正的新安装展示首次引导。
    /// 现有用户会在第一次判定时被归类为 legacy install 并直接视为已完成；
    /// 真正的新安装会被归类为 new install，在完成 onboarding 前始终继续展示。
    func shouldShowOnboarding(
        core: ClipinCore,
        permissionGranted: Bool,
        hadExistingStorageBeforeBootstrap: Bool
    ) -> Bool {
        guard !hasCompletedOnboarding else { return false }

        switch resolveOnboardingCohort(
            core: core,
            permissionGranted: permissionGranted,
            hadExistingStorageBeforeBootstrap: hadExistingStorageBeforeBootstrap
        ) {
        case .legacyInstall:
            markOnboardingCompleted()
            return false
        case .newInstall:
            return true
        }
    }

    func markOnboardingCompleted() {
        let nextVersion = Self.currentOnboardingVersion
        guard onboardingVersion != nextVersion else { return }
        onboardingVersion = nextVersion
        defaults.set(nextVersion, forKey: Keys.onboardingVersion)
    }

    /// 调试辅助：把 onboarding 还原为“未完成”，方便重复验证首次启动路径。
    func resetOnboardingForTesting() {
        onboardingVersion = 0
        onboardingCohort = nil
        defaults.removeObject(forKey: Keys.onboardingVersion)
        defaults.removeObject(forKey: Keys.onboardingCohort)
    }

    private func resolveOnboardingCohort(
        core: ClipinCore,
        permissionGranted: Bool,
        hadExistingStorageBeforeBootstrap: Bool
    ) -> OnboardingCohort {
        if let onboardingCohort {
            return onboardingCohort
        }

        let cohort: OnboardingCohort = looksLikeLegacyInstall(
            core: core,
            permissionGranted: permissionGranted,
            hadExistingStorageBeforeBootstrap: hadExistingStorageBeforeBootstrap
        ) ? .legacyInstall : .newInstall

        onboardingCohort = cohort
        defaults.set(cohort.rawValue, forKey: Keys.onboardingCohort)
        return cohort
    }

    private func looksLikeLegacyInstall(
        core: ClipinCore,
        permissionGranted: Bool,
        hadExistingStorageBeforeBootstrap: Bool
    ) -> Bool {
        if hadExistingStorageBeforeBootstrap {
            return true
        }

        if permissionGranted {
            return true
        }

        if !core.getListItems(limit: 1, offset: 0, typeFilter: nil).isEmpty {
            return true
        }

        return Self.legacyInstallKeys.contains { defaults.object(forKey: $0) != nil }
    }
}

enum AutoBackupInterval: String, CaseIterable {
    case onChange = "onChange"
    case daily    = "daily"
    case weekly   = "weekly"
    case monthly  = "monthly"

    var displayName: String {
        switch self {
        case .onChange: return NSLocalizedString("On Clipboard Change", comment: "")
        case .daily:    return NSLocalizedString("Daily", comment: "")
        case .weekly:   return NSLocalizedString("Weekly", comment: "")
        case .monthly:  return NSLocalizedString("Monthly", comment: "")
        }
    }

    /// 两次备份之间的最小间隔。nil = onChange 触发型，不使用定时器
    var backupInterval: TimeInterval? {
        switch self {
        case .onChange: return nil
        case .daily:    return 24 * 60 * 60
        case .weekly:   return 7 * 24 * 60 * 60
        case .monthly:  return 30 * 24 * 60 * 60
        }
    }

    /// 定时检查"是否逾期"的轮询间隔，远小于 backupInterval 以保证不漏触发
    var checkInterval: TimeInterval? {
        switch self {
        case .onChange: return nil
        case .daily:    return 60 * 60          // 每小时检查
        case .weekly:   return 6 * 60 * 60      // 每 6 小时检查
        case .monthly:  return 24 * 60 * 60     // 每天检查
        }
    }
}
